// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: api/v1/sig/sig.proto

package apiv1sig

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateComponentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateComponentRequest) Reset() {
	*x = CreateComponentRequest{}
	mi := &file_api_v1_sig_sig_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateComponentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateComponentRequest) ProtoMessage() {}

func (x *CreateComponentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sig_sig_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateComponentRequest.ProtoReflect.Descriptor instead.
func (*CreateComponentRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_sig_sig_proto_rawDescGZIP(), []int{0}
}

func (x *CreateComponentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateComponentRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type RetrieveComponentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveComponentRequest) Reset() {
	*x = RetrieveComponentRequest{}
	mi := &file_api_v1_sig_sig_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveComponentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveComponentRequest) ProtoMessage() {}

func (x *RetrieveComponentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sig_sig_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveComponentRequest.ProtoReflect.Descriptor instead.
func (*RetrieveComponentRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_sig_sig_proto_rawDescGZIP(), []int{1}
}

func (x *RetrieveComponentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RetrieveComponentRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type CreateInterComponentDependencyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The caller component.
	Caller *CreateInterComponentDependencyEndpointRequest `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`
	// The callees (API methods called by the component).
	Callees       []*CreateInterComponentDependencyEndpointRequest `protobuf:"bytes,2,rep,name=callees,proto3" json:"callees,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInterComponentDependencyRequest) Reset() {
	*x = CreateInterComponentDependencyRequest{}
	mi := &file_api_v1_sig_sig_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInterComponentDependencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInterComponentDependencyRequest) ProtoMessage() {}

func (x *CreateInterComponentDependencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sig_sig_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInterComponentDependencyRequest.ProtoReflect.Descriptor instead.
func (*CreateInterComponentDependencyRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_sig_sig_proto_rawDescGZIP(), []int{2}
}

func (x *CreateInterComponentDependencyRequest) GetCaller() *CreateInterComponentDependencyEndpointRequest {
	if x != nil {
		return x.Caller
	}
	return nil
}

func (x *CreateInterComponentDependencyRequest) GetCallees() []*CreateInterComponentDependencyEndpointRequest {
	if x != nil {
		return x.Callees
	}
	return nil
}

type CreateInterComponentDependencyEndpointRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the Endpoint, for a Component.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The Component the Endpoint exposes.
	Exposes       *CreateInterComponentDependencyEndpointComponentRequest `protobuf:"bytes,2,opt,name=exposes,proto3" json:"exposes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInterComponentDependencyEndpointRequest) Reset() {
	*x = CreateInterComponentDependencyEndpointRequest{}
	mi := &file_api_v1_sig_sig_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInterComponentDependencyEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInterComponentDependencyEndpointRequest) ProtoMessage() {}

func (x *CreateInterComponentDependencyEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sig_sig_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInterComponentDependencyEndpointRequest.ProtoReflect.Descriptor instead.
func (*CreateInterComponentDependencyEndpointRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_sig_sig_proto_rawDescGZIP(), []int{3}
}

func (x *CreateInterComponentDependencyEndpointRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateInterComponentDependencyEndpointRequest) GetExposes() *CreateInterComponentDependencyEndpointComponentRequest {
	if x != nil {
		return x.Exposes
	}
	return nil
}

type CreateInterComponentDependencyEndpointComponentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInterComponentDependencyEndpointComponentRequest) Reset() {
	*x = CreateInterComponentDependencyEndpointComponentRequest{}
	mi := &file_api_v1_sig_sig_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInterComponentDependencyEndpointComponentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInterComponentDependencyEndpointComponentRequest) ProtoMessage() {}

func (x *CreateInterComponentDependencyEndpointComponentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sig_sig_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInterComponentDependencyEndpointComponentRequest.ProtoReflect.Descriptor instead.
func (*CreateInterComponentDependencyEndpointComponentRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_sig_sig_proto_rawDescGZIP(), []int{4}
}

func (x *CreateInterComponentDependencyEndpointComponentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateInterComponentDependencyEndpointComponentRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Component struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Name    string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// The list of all known endpoints of the Component.
	Endpoints     []string `protobuf:"bytes,3,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Component) Reset() {
	*x = Component{}
	mi := &file_api_v1_sig_sig_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Component) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Component) ProtoMessage() {}

func (x *Component) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sig_sig_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Component.ProtoReflect.Descriptor instead.
func (*Component) Descriptor() ([]byte, []int) {
	return file_api_v1_sig_sig_proto_rawDescGZIP(), []int{5}
}

func (x *Component) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Component) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Component) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

var File_api_v1_sig_sig_proto protoreflect.FileDescriptor

const file_api_v1_sig_sig_proto_rawDesc = "" +
	"\n" +
	"\x14api/v1/sig/sig.proto\x12\n" +
	"api.v1.sig\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"t\n" +
	"\x16CreateComponentRequest\x12-\n" +
	"\x04name\x18\x01 \x01(\tB\x19\x92A\x12J\x10\"some-component\"\xe2A\x01\x02R\x04name\x12+\n" +
	"\aversion\x18\x02 \x01(\tB\x11\x92A\n" +
	"J\b\"v2.3.0\"\xe2A\x01\x02R\aversion\"v\n" +
	"\x18RetrieveComponentRequest\x12-\n" +
	"\x04name\x18\x01 \x01(\tB\x19\x92A\x12J\x10\"some-component\"\xe2A\x01\x02R\x04name\x12+\n" +
	"\aversion\x18\x02 \x01(\tB\x11\x92A\n" +
	"J\b\"v2.3.0\"\xe2A\x01\x02R\aversion\"\xcf\x01\n" +
	"%CreateInterComponentDependencyRequest\x12Q\n" +
	"\x06caller\x18\x01 \x01(\v29.api.v1.sig.CreateInterComponentDependencyEndpointRequestR\x06caller\x12S\n" +
	"\acallees\x18\x02 \x03(\v29.api.v1.sig.CreateInterComponentDependencyEndpointRequestR\acallees\"\xdb\x01\n" +
	"-CreateInterComponentDependencyEndpointRequest\x120\n" +
	"\x04name\x18\x01 \x01(\tB\x1c\x92A\x15J\x13\"api/vx.SomeMethod\"\xe2A\x01\x02R\x04name\x12x\n" +
	"\aexposes\x18\x02 \x01(\v2B.api.v1.sig.CreateInterComponentDependencyEndpointComponentRequestB\x1a\x92A\x13J\x11\"other-component\"\xe2A\x01\x02R\aexposes\"\x94\x01\n" +
	"6CreateInterComponentDependencyEndpointComponentRequest\x12-\n" +
	"\x04name\x18\x01 \x01(\tB\x19\x92A\x12J\x10\"some-component\"\xe2A\x01\x02R\x04name\x12+\n" +
	"\aversion\x18\x02 \x01(\tB\x11\x92A\n" +
	"J\b\"v2.3.0\"\xe2A\x01\x02R\aversion\"\x85\x01\n" +
	"\tComponent\x12-\n" +
	"\x04name\x18\x01 \x01(\tB\x19\x92A\x12J\x10\"some-component\"\xe2A\x01\x02R\x04name\x12+\n" +
	"\aversion\x18\x02 \x01(\tB\x11\x92A\n" +
	"J\b\"v2.3.0\"\xe2A\x01\x02R\aversion\x12\x1c\n" +
	"\tendpoints\x18\x03 \x03(\tR\tendpoints2\xd5\x03\n" +
	"\x03SIG\x12n\n" +
	"\x0fCreateComponent\x12\".api.v1.sig.CreateComponentRequest\x1a\x15.api.v1.sig.Component\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/sig/component\x12o\n" +
	"\x11RetrieveComponent\x12$.api.v1.sig.RetrieveComponentRequest\x1a\x15.api.v1.sig.Component\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/sig/component\x12\x9e\x01\n" +
	"\x1eCreateInterComponentDependency\x121.api.v1.sig.CreateInterComponentDependencyRequest\x1a\x16.google.protobuf.Empty\"1\x82\xd3\xe4\x93\x02+:\x01*\"&/api/v1/sig/inter-component-dependency\x12L\n" +
	"\x05Reset\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x13\x82\xd3\xe4\x93\x02\r*\v/api/v1/sigB4Z2github.com/pandatix/godepgraph/api/v1/sig;apiv1sigb\x06proto3"

var (
	file_api_v1_sig_sig_proto_rawDescOnce sync.Once
	file_api_v1_sig_sig_proto_rawDescData []byte
)

func file_api_v1_sig_sig_proto_rawDescGZIP() []byte {
	file_api_v1_sig_sig_proto_rawDescOnce.Do(func() {
		file_api_v1_sig_sig_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_sig_sig_proto_rawDesc), len(file_api_v1_sig_sig_proto_rawDesc)))
	})
	return file_api_v1_sig_sig_proto_rawDescData
}

var file_api_v1_sig_sig_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_v1_sig_sig_proto_goTypes = []any{
	(*CreateComponentRequest)(nil),                                 // 0: api.v1.sig.CreateComponentRequest
	(*RetrieveComponentRequest)(nil),                               // 1: api.v1.sig.RetrieveComponentRequest
	(*CreateInterComponentDependencyRequest)(nil),                  // 2: api.v1.sig.CreateInterComponentDependencyRequest
	(*CreateInterComponentDependencyEndpointRequest)(nil),          // 3: api.v1.sig.CreateInterComponentDependencyEndpointRequest
	(*CreateInterComponentDependencyEndpointComponentRequest)(nil), // 4: api.v1.sig.CreateInterComponentDependencyEndpointComponentRequest
	(*Component)(nil),     // 5: api.v1.sig.Component
	(*emptypb.Empty)(nil), // 6: google.protobuf.Empty
}
var file_api_v1_sig_sig_proto_depIdxs = []int32{
	3, // 0: api.v1.sig.CreateInterComponentDependencyRequest.caller:type_name -> api.v1.sig.CreateInterComponentDependencyEndpointRequest
	3, // 1: api.v1.sig.CreateInterComponentDependencyRequest.callees:type_name -> api.v1.sig.CreateInterComponentDependencyEndpointRequest
	4, // 2: api.v1.sig.CreateInterComponentDependencyEndpointRequest.exposes:type_name -> api.v1.sig.CreateInterComponentDependencyEndpointComponentRequest
	0, // 3: api.v1.sig.SIG.CreateComponent:input_type -> api.v1.sig.CreateComponentRequest
	1, // 4: api.v1.sig.SIG.RetrieveComponent:input_type -> api.v1.sig.RetrieveComponentRequest
	2, // 5: api.v1.sig.SIG.CreateInterComponentDependency:input_type -> api.v1.sig.CreateInterComponentDependencyRequest
	6, // 6: api.v1.sig.SIG.Reset:input_type -> google.protobuf.Empty
	5, // 7: api.v1.sig.SIG.CreateComponent:output_type -> api.v1.sig.Component
	5, // 8: api.v1.sig.SIG.RetrieveComponent:output_type -> api.v1.sig.Component
	6, // 9: api.v1.sig.SIG.CreateInterComponentDependency:output_type -> google.protobuf.Empty
	6, // 10: api.v1.sig.SIG.Reset:output_type -> google.protobuf.Empty
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_v1_sig_sig_proto_init() }
func file_api_v1_sig_sig_proto_init() {
	if File_api_v1_sig_sig_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_sig_sig_proto_rawDesc), len(file_api_v1_sig_sig_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_sig_sig_proto_goTypes,
		DependencyIndexes: file_api_v1_sig_sig_proto_depIdxs,
		MessageInfos:      file_api_v1_sig_sig_proto_msgTypes,
	}.Build()
	File_api_v1_sig_sig_proto = out.File
	file_api_v1_sig_sig_proto_goTypes = nil
	file_api_v1_sig_sig_proto_depIdxs = nil
}
