// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: api/v1/rdg/rdg.proto

package apiv1rdg

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateStackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStackRequest) Reset() {
	*x = CreateStackRequest{}
	mi := &file_api_v1_rdg_rdg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStackRequest) ProtoMessage() {}

func (x *CreateStackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_rdg_rdg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStackRequest.ProtoReflect.Descriptor instead.
func (*CreateStackRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_rdg_rdg_proto_rawDescGZIP(), []int{0}
}

func (x *CreateStackRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type Stack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stack) Reset() {
	*x = Stack{}
	mi := &file_api_v1_rdg_rdg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stack) ProtoMessage() {}

func (x *Stack) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_rdg_rdg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stack.ProtoReflect.Descriptor instead.
func (*Stack) Descriptor() ([]byte, []int) {
	return file_api_v1_rdg_rdg_proto_rawDescGZIP(), []int{1}
}

var File_api_v1_rdg_rdg_proto protoreflect.FileDescriptor

const file_api_v1_rdg_rdg_proto_rawDesc = "" +
	"\n" +
	"\x14api/v1/rdg/rdg.proto\x12\n" +
	"api.v1.rdg\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"S\n" +
	"\x12CreateStackRequest\x12=\n" +
	"\x03uri\x18\x01 \x01(\tB+\x92A$J\"\"https://webserver.tld/state.json\"\xe2A\x01\x02R\x03uri\"\a\n" +
	"\x05Stack2\xad\x01\n" +
	"\x03RDG\x12X\n" +
	"\vCreateStack\x12\x1e.api.v1.rdg.CreateStackRequest\x1a\x11.api.v1.rdg.Stack\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/api/v1/rdg\x12L\n" +
	"\x05Reset\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x13\x82\xd3\xe4\x93\x02\r*\v/api/v1/rdgBFZDgit.cvewatcher.la-ruche.fr/CVEWatcher/godepgraph/api/v1/rdg;apiv1rdgb\x06proto3"

var (
	file_api_v1_rdg_rdg_proto_rawDescOnce sync.Once
	file_api_v1_rdg_rdg_proto_rawDescData []byte
)

func file_api_v1_rdg_rdg_proto_rawDescGZIP() []byte {
	file_api_v1_rdg_rdg_proto_rawDescOnce.Do(func() {
		file_api_v1_rdg_rdg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_rdg_rdg_proto_rawDesc), len(file_api_v1_rdg_rdg_proto_rawDesc)))
	})
	return file_api_v1_rdg_rdg_proto_rawDescData
}

var file_api_v1_rdg_rdg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_v1_rdg_rdg_proto_goTypes = []any{
	(*CreateStackRequest)(nil), // 0: api.v1.rdg.CreateStackRequest
	(*Stack)(nil),              // 1: api.v1.rdg.Stack
	(*emptypb.Empty)(nil),      // 2: google.protobuf.Empty
}
var file_api_v1_rdg_rdg_proto_depIdxs = []int32{
	0, // 0: api.v1.rdg.RDG.CreateStack:input_type -> api.v1.rdg.CreateStackRequest
	2, // 1: api.v1.rdg.RDG.Reset:input_type -> google.protobuf.Empty
	1, // 2: api.v1.rdg.RDG.CreateStack:output_type -> api.v1.rdg.Stack
	2, // 3: api.v1.rdg.RDG.Reset:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_rdg_rdg_proto_init() }
func file_api_v1_rdg_rdg_proto_init() {
	if File_api_v1_rdg_rdg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_rdg_rdg_proto_rawDesc), len(file_api_v1_rdg_rdg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_rdg_rdg_proto_goTypes,
		DependencyIndexes: file_api_v1_rdg_rdg_proto_depIdxs,
		MessageInfos:      file_api_v1_rdg_rdg_proto_msgTypes,
	}.Build()
	File_api_v1_rdg_rdg_proto = out.File
	file_api_v1_rdg_rdg_proto_goTypes = nil
	file_api_v1_rdg_rdg_proto_depIdxs = nil
}
