// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: api/v1/alg4/alg4.proto

package apiv1alg4

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateVulnerabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Treatens      string                 `protobuf:"bytes,2,opt,name=treatens,proto3" json:"treatens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVulnerabilityRequest) Reset() {
	*x = CreateVulnerabilityRequest{}
	mi := &file_api_v1_alg4_alg4_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVulnerabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVulnerabilityRequest) ProtoMessage() {}

func (x *CreateVulnerabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_alg4_alg4_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVulnerabilityRequest.ProtoReflect.Descriptor instead.
func (*CreateVulnerabilityRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_alg4_alg4_proto_rawDescGZIP(), []int{0}
}

func (x *CreateVulnerabilityRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *CreateVulnerabilityRequest) GetTreatens() string {
	if x != nil {
		return x.Treatens
	}
	return ""
}

type RetrieveVulnerabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveVulnerabilityRequest) Reset() {
	*x = RetrieveVulnerabilityRequest{}
	mi := &file_api_v1_alg4_alg4_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveVulnerabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveVulnerabilityRequest) ProtoMessage() {}

func (x *RetrieveVulnerabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_alg4_alg4_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveVulnerabilityRequest.ProtoReflect.Descriptor instead.
func (*RetrieveVulnerabilityRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_alg4_alg4_proto_rawDescGZIP(), []int{1}
}

func (x *RetrieveVulnerabilityRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type RetrieveSymbolVulnerabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveSymbolVulnerabilitiesRequest) Reset() {
	*x = RetrieveSymbolVulnerabilitiesRequest{}
	mi := &file_api_v1_alg4_alg4_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveSymbolVulnerabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveSymbolVulnerabilitiesRequest) ProtoMessage() {}

func (x *RetrieveSymbolVulnerabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_alg4_alg4_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveSymbolVulnerabilitiesRequest.ProtoReflect.Descriptor instead.
func (*RetrieveSymbolVulnerabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_alg4_alg4_proto_rawDescGZIP(), []int{2}
}

func (x *RetrieveSymbolVulnerabilitiesRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type Vulnerabilities struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Vulnerabilities []string               `protobuf:"bytes,1,rep,name=vulnerabilities,proto3" json:"vulnerabilities,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Vulnerabilities) Reset() {
	*x = Vulnerabilities{}
	mi := &file_api_v1_alg4_alg4_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vulnerabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vulnerabilities) ProtoMessage() {}

func (x *Vulnerabilities) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_alg4_alg4_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vulnerabilities.ProtoReflect.Descriptor instead.
func (*Vulnerabilities) Descriptor() ([]byte, []int) {
	return file_api_v1_alg4_alg4_proto_rawDescGZIP(), []int{3}
}

func (x *Vulnerabilities) GetVulnerabilities() []string {
	if x != nil {
		return x.Vulnerabilities
	}
	return nil
}

type DeleteVulnerabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVulnerabilityRequest) Reset() {
	*x = DeleteVulnerabilityRequest{}
	mi := &file_api_v1_alg4_alg4_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVulnerabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVulnerabilityRequest) ProtoMessage() {}

func (x *DeleteVulnerabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_alg4_alg4_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVulnerabilityRequest.ProtoReflect.Descriptor instead.
func (*DeleteVulnerabilityRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_alg4_alg4_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteVulnerabilityRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type Vulnerability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Treatens      string                 `protobuf:"bytes,2,opt,name=treatens,proto3" json:"treatens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vulnerability) Reset() {
	*x = Vulnerability{}
	mi := &file_api_v1_alg4_alg4_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vulnerability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vulnerability) ProtoMessage() {}

func (x *Vulnerability) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_alg4_alg4_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vulnerability.ProtoReflect.Descriptor instead.
func (*Vulnerability) Descriptor() ([]byte, []int) {
	return file_api_v1_alg4_alg4_proto_rawDescGZIP(), []int{5}
}

func (x *Vulnerability) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *Vulnerability) GetTreatens() string {
	if x != nil {
		return x.Treatens
	}
	return ""
}

type CreateServesRequest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Symbol        *CreateServesSymbolRequest   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Endpoint      *CreateServesEndpointRequest `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServesRequest) Reset() {
	*x = CreateServesRequest{}
	mi := &file_api_v1_alg4_alg4_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServesRequest) ProtoMessage() {}

func (x *CreateServesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_alg4_alg4_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServesRequest.ProtoReflect.Descriptor instead.
func (*CreateServesRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_alg4_alg4_proto_rawDescGZIP(), []int{6}
}

func (x *CreateServesRequest) GetSymbol() *CreateServesSymbolRequest {
	if x != nil {
		return x.Symbol
	}
	return nil
}

func (x *CreateServesRequest) GetEndpoint() *CreateServesEndpointRequest {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

type CreateServesSymbolRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The symbol identity.
	Identity      string `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServesSymbolRequest) Reset() {
	*x = CreateServesSymbolRequest{}
	mi := &file_api_v1_alg4_alg4_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServesSymbolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServesSymbolRequest) ProtoMessage() {}

func (x *CreateServesSymbolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_alg4_alg4_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServesSymbolRequest.ProtoReflect.Descriptor instead.
func (*CreateServesSymbolRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_alg4_alg4_proto_rawDescGZIP(), []int{7}
}

func (x *CreateServesSymbolRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type CreateServesEndpointRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Name          string                        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Exposes       *CreateServesComponentRequest `protobuf:"bytes,2,opt,name=exposes,proto3" json:"exposes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServesEndpointRequest) Reset() {
	*x = CreateServesEndpointRequest{}
	mi := &file_api_v1_alg4_alg4_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServesEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServesEndpointRequest) ProtoMessage() {}

func (x *CreateServesEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_alg4_alg4_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServesEndpointRequest.ProtoReflect.Descriptor instead.
func (*CreateServesEndpointRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_alg4_alg4_proto_rawDescGZIP(), []int{8}
}

func (x *CreateServesEndpointRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateServesEndpointRequest) GetExposes() *CreateServesComponentRequest {
	if x != nil {
		return x.Exposes
	}
	return nil
}

type CreateServesComponentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServesComponentRequest) Reset() {
	*x = CreateServesComponentRequest{}
	mi := &file_api_v1_alg4_alg4_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServesComponentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServesComponentRequest) ProtoMessage() {}

func (x *CreateServesComponentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_alg4_alg4_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServesComponentRequest.ProtoReflect.Descriptor instead.
func (*CreateServesComponentRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_alg4_alg4_proto_rawDescGZIP(), []int{9}
}

func (x *CreateServesComponentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateServesComponentRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type LibraryOrRefinement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LibraryOrRefinement) Reset() {
	*x = LibraryOrRefinement{}
	mi := &file_api_v1_alg4_alg4_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LibraryOrRefinement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibraryOrRefinement) ProtoMessage() {}

func (x *LibraryOrRefinement) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_alg4_alg4_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LibraryOrRefinement.ProtoReflect.Descriptor instead.
func (*LibraryOrRefinement) Descriptor() ([]byte, []int) {
	return file_api_v1_alg4_alg4_proto_rawDescGZIP(), []int{10}
}

func (x *LibraryOrRefinement) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LibraryOrRefinement) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type CreateBindingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Library       *LibraryOrRefinement   `protobuf:"bytes,1,opt,name=library,proto3,oneof" json:"library,omitempty"`
	Component     *LibraryOrRefinement   `protobuf:"bytes,2,opt,name=component,proto3,oneof" json:"component,omitempty"`
	Asset         *LibraryOrRefinement   `protobuf:"bytes,3,opt,name=asset,proto3,oneof" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBindingRequest) Reset() {
	*x = CreateBindingRequest{}
	mi := &file_api_v1_alg4_alg4_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBindingRequest) ProtoMessage() {}

func (x *CreateBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_alg4_alg4_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBindingRequest.ProtoReflect.Descriptor instead.
func (*CreateBindingRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_alg4_alg4_proto_rawDescGZIP(), []int{11}
}

func (x *CreateBindingRequest) GetLibrary() *LibraryOrRefinement {
	if x != nil {
		return x.Library
	}
	return nil
}

func (x *CreateBindingRequest) GetComponent() *LibraryOrRefinement {
	if x != nil {
		return x.Component
	}
	return nil
}

func (x *CreateBindingRequest) GetAsset() *LibraryOrRefinement {
	if x != nil {
		return x.Asset
	}
	return nil
}

// A binding represents any specialization of a Library as per
// proposed model in Figure 1.
// It depends on the usage of CDN, RDG and SIG, combined together
// as per proposed model in Figure 3.
type Binding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Library       *LibraryOrRefinement   `protobuf:"bytes,1,opt,name=library,proto3,oneof" json:"library,omitempty"`
	Component     *LibraryOrRefinement   `protobuf:"bytes,2,opt,name=component,proto3,oneof" json:"component,omitempty"`
	Asset         *LibraryOrRefinement   `protobuf:"bytes,3,opt,name=asset,proto3,oneof" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Binding) Reset() {
	*x = Binding{}
	mi := &file_api_v1_alg4_alg4_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Binding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Binding) ProtoMessage() {}

func (x *Binding) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_alg4_alg4_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Binding.ProtoReflect.Descriptor instead.
func (*Binding) Descriptor() ([]byte, []int) {
	return file_api_v1_alg4_alg4_proto_rawDescGZIP(), []int{12}
}

func (x *Binding) GetLibrary() *LibraryOrRefinement {
	if x != nil {
		return x.Library
	}
	return nil
}

func (x *Binding) GetComponent() *LibraryOrRefinement {
	if x != nil {
		return x.Component
	}
	return nil
}

func (x *Binding) GetAsset() *LibraryOrRefinement {
	if x != nil {
		return x.Asset
	}
	return nil
}

var File_api_v1_alg4_alg4_proto protoreflect.FileDescriptor

const file_api_v1_alg4_alg4_proto_rawDesc = "" +
	"\n" +
	"\x16api/v1/alg4/alg4.proto\x12\vapi.v1.alg4\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x94\x01\n" +
	"\x1aCreateVulnerabilityRequest\x125\n" +
	"\bidentity\x18\x01 \x01(\tB\x19\x92A\x12J\x10\"CVE-1000-01234\"\xe2A\x01\x02R\bidentity\x12?\n" +
	"\btreatens\x18\x02 \x01(\tB#\x92A\x1cJ\x1a\"internal/stringslite.Cut\"\xe2A\x01\x02R\btreatens\"U\n" +
	"\x1cRetrieveVulnerabilityRequest\x125\n" +
	"\bidentity\x18\x01 \x01(\tB\x19\x92A\x12J\x10\"CVE-1000-01234\"\xe2A\x01\x02R\bidentity\">\n" +
	"$RetrieveSymbolVulnerabilitiesRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\";\n" +
	"\x0fVulnerabilities\x12(\n" +
	"\x0fvulnerabilities\x18\x01 \x03(\tR\x0fvulnerabilities\"S\n" +
	"\x1aDeleteVulnerabilityRequest\x125\n" +
	"\bidentity\x18\x01 \x01(\tB\x19\x92A\x12J\x10\"CVE-1000-01234\"\xe2A\x01\x02R\bidentity\"\x87\x01\n" +
	"\rVulnerability\x125\n" +
	"\bidentity\x18\x01 \x01(\tB\x19\x92A\x12J\x10\"CVE-1000-01234\"\xe2A\x01\x02R\bidentity\x12?\n" +
	"\btreatens\x18\x02 \x01(\tB#\x92A\x1cJ\x1a\"internal/stringslite.Cut\"\xe2A\x01\x02R\btreatens\"\x9b\x01\n" +
	"\x13CreateServesRequest\x12>\n" +
	"\x06symbol\x18\x01 \x01(\v2&.api.v1.alg4.CreateServesSymbolRequestR\x06symbol\x12D\n" +
	"\bendpoint\x18\x02 \x01(\v2(.api.v1.alg4.CreateServesEndpointRequestR\bendpoint\"\\\n" +
	"\x19CreateServesSymbolRequest\x12?\n" +
	"\bidentity\x18\x01 \x01(\tB#\x92A\x1cJ\x1a\"internal/stringslite.Cut\"\xe2A\x01\x02R\bidentity\"v\n" +
	"\x1bCreateServesEndpointRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12C\n" +
	"\aexposes\x18\x02 \x01(\v2).api.v1.alg4.CreateServesComponentRequestR\aexposes\"\x82\x01\n" +
	"\x1cCreateServesComponentRequest\x125\n" +
	"\x04name\x18\x01 \x01(\tB!\x92A\x1aJ\x18\"github.com/gorilla/mux\"\xe2A\x01\x02R\x04name\x12+\n" +
	"\aversion\x18\x02 \x01(\tB\x11\x92A\n" +
	"J\b\"v1.8.1\"\xe2A\x01\x02R\aversion\"y\n" +
	"\x13LibraryOrRefinement\x125\n" +
	"\x04name\x18\x01 \x01(\tB!\x92A\x1aJ\x18\"github.com/gorilla/mux\"\xe2A\x01\x02R\x04name\x12+\n" +
	"\aversion\x18\x02 \x01(\tB\x11\x92A\n" +
	"J\b\"v1.8.1\"\xe2A\x01\x02R\aversion\"\xfd\x01\n" +
	"\x14CreateBindingRequest\x12?\n" +
	"\alibrary\x18\x01 \x01(\v2 .api.v1.alg4.LibraryOrRefinementH\x00R\alibrary\x88\x01\x01\x12C\n" +
	"\tcomponent\x18\x02 \x01(\v2 .api.v1.alg4.LibraryOrRefinementH\x01R\tcomponent\x88\x01\x01\x12;\n" +
	"\x05asset\x18\x03 \x01(\v2 .api.v1.alg4.LibraryOrRefinementH\x02R\x05asset\x88\x01\x01B\n" +
	"\n" +
	"\b_libraryB\f\n" +
	"\n" +
	"_componentB\b\n" +
	"\x06_asset\"\xf0\x01\n" +
	"\aBinding\x12?\n" +
	"\alibrary\x18\x01 \x01(\v2 .api.v1.alg4.LibraryOrRefinementH\x00R\alibrary\x88\x01\x01\x12C\n" +
	"\tcomponent\x18\x02 \x01(\v2 .api.v1.alg4.LibraryOrRefinementH\x01R\tcomponent\x88\x01\x01\x12;\n" +
	"\x05asset\x18\x03 \x01(\v2 .api.v1.alg4.LibraryOrRefinementH\x02R\x05asset\x88\x01\x01B\n" +
	"\n" +
	"\b_libraryB\f\n" +
	"\n" +
	"_componentB\b\n" +
	"\x06_asset2\xfb\x05\n" +
	"\x04Alg4\x12}\n" +
	"\x13CreateVulnerability\x12'.api.v1.alg4.CreateVulnerabilityRequest\x1a\x16.google.protobuf.Empty\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/alg4/vulnerability\x12\x82\x01\n" +
	"\x15RetrieveVulnerability\x12).api.v1.alg4.RetrieveVulnerabilityRequest\x1a\x1a.api.v1.alg4.Vulnerability\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/alg4/vulnerability\x12\x9d\x01\n" +
	"\x1dRetrieveSymbolVulnerabilities\x121.api.v1.alg4.RetrieveSymbolVulnerabilitiesRequest\x1a\x1c.api.v1.alg4.Vulnerabilities\"+\x82\xd3\xe4\x93\x02%\x12#/api/v1/alg4/vulnerability/{symbol}\x12z\n" +
	"\x13DeleteVulnerability\x12'.api.v1.alg4.DeleteVulnerabilityRequest\x1a\x16.google.protobuf.Empty\"\"\x82\xd3\xe4\x93\x02\x1c*\x1a/api/v1/alg4/vulnerability\x12i\n" +
	"\rCreateBinding\x12!.api.v1.alg4.CreateBindingRequest\x1a\x14.api.v1.alg4.Binding\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/alg4/binding\x12h\n" +
	"\fCreateServes\x12 .api.v1.alg4.CreateServesRequest\x1a\x16.google.protobuf.Empty\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/alg4/servesB6Z4github.com/pandatix/godepgraph/api/v1/alg4;apiv1alg4b\x06proto3"

var (
	file_api_v1_alg4_alg4_proto_rawDescOnce sync.Once
	file_api_v1_alg4_alg4_proto_rawDescData []byte
)

func file_api_v1_alg4_alg4_proto_rawDescGZIP() []byte {
	file_api_v1_alg4_alg4_proto_rawDescOnce.Do(func() {
		file_api_v1_alg4_alg4_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_alg4_alg4_proto_rawDesc), len(file_api_v1_alg4_alg4_proto_rawDesc)))
	})
	return file_api_v1_alg4_alg4_proto_rawDescData
}

var file_api_v1_alg4_alg4_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_v1_alg4_alg4_proto_goTypes = []any{
	(*CreateVulnerabilityRequest)(nil),           // 0: api.v1.alg4.CreateVulnerabilityRequest
	(*RetrieveVulnerabilityRequest)(nil),         // 1: api.v1.alg4.RetrieveVulnerabilityRequest
	(*RetrieveSymbolVulnerabilitiesRequest)(nil), // 2: api.v1.alg4.RetrieveSymbolVulnerabilitiesRequest
	(*Vulnerabilities)(nil),                      // 3: api.v1.alg4.Vulnerabilities
	(*DeleteVulnerabilityRequest)(nil),           // 4: api.v1.alg4.DeleteVulnerabilityRequest
	(*Vulnerability)(nil),                        // 5: api.v1.alg4.Vulnerability
	(*CreateServesRequest)(nil),                  // 6: api.v1.alg4.CreateServesRequest
	(*CreateServesSymbolRequest)(nil),            // 7: api.v1.alg4.CreateServesSymbolRequest
	(*CreateServesEndpointRequest)(nil),          // 8: api.v1.alg4.CreateServesEndpointRequest
	(*CreateServesComponentRequest)(nil),         // 9: api.v1.alg4.CreateServesComponentRequest
	(*LibraryOrRefinement)(nil),                  // 10: api.v1.alg4.LibraryOrRefinement
	(*CreateBindingRequest)(nil),                 // 11: api.v1.alg4.CreateBindingRequest
	(*Binding)(nil),                              // 12: api.v1.alg4.Binding
	(*emptypb.Empty)(nil),                        // 13: google.protobuf.Empty
}
var file_api_v1_alg4_alg4_proto_depIdxs = []int32{
	7,  // 0: api.v1.alg4.CreateServesRequest.symbol:type_name -> api.v1.alg4.CreateServesSymbolRequest
	8,  // 1: api.v1.alg4.CreateServesRequest.endpoint:type_name -> api.v1.alg4.CreateServesEndpointRequest
	9,  // 2: api.v1.alg4.CreateServesEndpointRequest.exposes:type_name -> api.v1.alg4.CreateServesComponentRequest
	10, // 3: api.v1.alg4.CreateBindingRequest.library:type_name -> api.v1.alg4.LibraryOrRefinement
	10, // 4: api.v1.alg4.CreateBindingRequest.component:type_name -> api.v1.alg4.LibraryOrRefinement
	10, // 5: api.v1.alg4.CreateBindingRequest.asset:type_name -> api.v1.alg4.LibraryOrRefinement
	10, // 6: api.v1.alg4.Binding.library:type_name -> api.v1.alg4.LibraryOrRefinement
	10, // 7: api.v1.alg4.Binding.component:type_name -> api.v1.alg4.LibraryOrRefinement
	10, // 8: api.v1.alg4.Binding.asset:type_name -> api.v1.alg4.LibraryOrRefinement
	0,  // 9: api.v1.alg4.Alg4.CreateVulnerability:input_type -> api.v1.alg4.CreateVulnerabilityRequest
	1,  // 10: api.v1.alg4.Alg4.RetrieveVulnerability:input_type -> api.v1.alg4.RetrieveVulnerabilityRequest
	2,  // 11: api.v1.alg4.Alg4.RetrieveSymbolVulnerabilities:input_type -> api.v1.alg4.RetrieveSymbolVulnerabilitiesRequest
	4,  // 12: api.v1.alg4.Alg4.DeleteVulnerability:input_type -> api.v1.alg4.DeleteVulnerabilityRequest
	11, // 13: api.v1.alg4.Alg4.CreateBinding:input_type -> api.v1.alg4.CreateBindingRequest
	6,  // 14: api.v1.alg4.Alg4.CreateServes:input_type -> api.v1.alg4.CreateServesRequest
	13, // 15: api.v1.alg4.Alg4.CreateVulnerability:output_type -> google.protobuf.Empty
	5,  // 16: api.v1.alg4.Alg4.RetrieveVulnerability:output_type -> api.v1.alg4.Vulnerability
	3,  // 17: api.v1.alg4.Alg4.RetrieveSymbolVulnerabilities:output_type -> api.v1.alg4.Vulnerabilities
	13, // 18: api.v1.alg4.Alg4.DeleteVulnerability:output_type -> google.protobuf.Empty
	12, // 19: api.v1.alg4.Alg4.CreateBinding:output_type -> api.v1.alg4.Binding
	13, // 20: api.v1.alg4.Alg4.CreateServes:output_type -> google.protobuf.Empty
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_v1_alg4_alg4_proto_init() }
func file_api_v1_alg4_alg4_proto_init() {
	if File_api_v1_alg4_alg4_proto != nil {
		return
	}
	file_api_v1_alg4_alg4_proto_msgTypes[11].OneofWrappers = []any{}
	file_api_v1_alg4_alg4_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_alg4_alg4_proto_rawDesc), len(file_api_v1_alg4_alg4_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_alg4_alg4_proto_goTypes,
		DependencyIndexes: file_api_v1_alg4_alg4_proto_depIdxs,
		MessageInfos:      file_api_v1_alg4_alg4_proto_msgTypes,
	}.Build()
	File_api_v1_alg4_alg4_proto = out.File
	file_api_v1_alg4_alg4_proto_goTypes = nil
	file_api_v1_alg4_alg4_proto_depIdxs = nil
}
