// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: api/v1/cdn/cdn.proto

package apiv1cdn

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateLibraryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Go module to analyze.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The Go module's version.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Whether to include test dependencies.
	Test          *bool `protobuf:"varint,3,opt,name=test,proto3,oneof" json:"test,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLibraryRequest) Reset() {
	*x = CreateLibraryRequest{}
	mi := &file_api_v1_cdn_cdn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLibraryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLibraryRequest) ProtoMessage() {}

func (x *CreateLibraryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_cdn_cdn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLibraryRequest.ProtoReflect.Descriptor instead.
func (*CreateLibraryRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_cdn_cdn_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLibraryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateLibraryRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CreateLibraryRequest) GetTest() bool {
	if x != nil && x.Test != nil {
		return *x.Test
	}
	return false
}

type RetrieveLibraryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Go module to retrieve.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The Go module's version to retrieve.
	Version       string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveLibraryRequest) Reset() {
	*x = RetrieveLibraryRequest{}
	mi := &file_api_v1_cdn_cdn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveLibraryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveLibraryRequest) ProtoMessage() {}

func (x *RetrieveLibraryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_cdn_cdn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveLibraryRequest.ProtoReflect.Descriptor instead.
func (*RetrieveLibraryRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_cdn_cdn_proto_rawDescGZIP(), []int{1}
}

func (x *RetrieveLibraryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RetrieveLibraryRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type RetrieveSymbolASTDependenciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        *Symbol                `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveSymbolASTDependenciesRequest) Reset() {
	*x = RetrieveSymbolASTDependenciesRequest{}
	mi := &file_api_v1_cdn_cdn_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveSymbolASTDependenciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveSymbolASTDependenciesRequest) ProtoMessage() {}

func (x *RetrieveSymbolASTDependenciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_cdn_cdn_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveSymbolASTDependenciesRequest.ProtoReflect.Descriptor instead.
func (*RetrieveSymbolASTDependenciesRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_cdn_cdn_proto_rawDescGZIP(), []int{2}
}

func (x *RetrieveSymbolASTDependenciesRequest) GetSymbol() *Symbol {
	if x != nil {
		return x.Symbol
	}
	return nil
}

type SymbolDepGraph struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *Symbol                `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            []*Symbol              `protobuf:"bytes,2,rep,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymbolDepGraph) Reset() {
	*x = SymbolDepGraph{}
	mi := &file_api_v1_cdn_cdn_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymbolDepGraph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolDepGraph) ProtoMessage() {}

func (x *SymbolDepGraph) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_cdn_cdn_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolDepGraph.ProtoReflect.Descriptor instead.
func (*SymbolDepGraph) Descriptor() ([]byte, []int) {
	return file_api_v1_cdn_cdn_proto_rawDescGZIP(), []int{3}
}

func (x *SymbolDepGraph) GetFrom() *Symbol {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *SymbolDepGraph) GetTo() []*Symbol {
	if x != nil {
		return x.To
	}
	return nil
}

type DependencyGraph struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Go module to retrieve.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The Go module's version to retrieve.
	Version       string           `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Provide       []*Symbol        `protobuf:"bytes,3,rep,name=provide,proto3" json:"provide,omitempty"`
	Dependencies  []*ASTDependency `protobuf:"bytes,4,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DependencyGraph) Reset() {
	*x = DependencyGraph{}
	mi := &file_api_v1_cdn_cdn_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependencyGraph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependencyGraph) ProtoMessage() {}

func (x *DependencyGraph) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_cdn_cdn_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependencyGraph.ProtoReflect.Descriptor instead.
func (*DependencyGraph) Descriptor() ([]byte, []int) {
	return file_api_v1_cdn_cdn_proto_rawDescGZIP(), []int{4}
}

func (x *DependencyGraph) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DependencyGraph) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DependencyGraph) GetProvide() []*Symbol {
	if x != nil {
		return x.Provide
	}
	return nil
}

func (x *DependencyGraph) GetDependencies() []*ASTDependency {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

type Symbol struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The symbol identity.
	Identity      string `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Symbol) Reset() {
	*x = Symbol{}
	mi := &file_api_v1_cdn_cdn_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Symbol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Symbol) ProtoMessage() {}

func (x *Symbol) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_cdn_cdn_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Symbol.ProtoReflect.Descriptor instead.
func (*Symbol) Descriptor() ([]byte, []int) {
	return file_api_v1_cdn_cdn_proto_rawDescGZIP(), []int{5}
}

func (x *Symbol) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type ASTDependency struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The symbol identity it depends from.
	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// The symbol identites it depends upon.
	To            []string `protobuf:"bytes,2,rep,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ASTDependency) Reset() {
	*x = ASTDependency{}
	mi := &file_api_v1_cdn_cdn_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ASTDependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ASTDependency) ProtoMessage() {}

func (x *ASTDependency) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_cdn_cdn_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ASTDependency.ProtoReflect.Descriptor instead.
func (*ASTDependency) Descriptor() ([]byte, []int) {
	return file_api_v1_cdn_cdn_proto_rawDescGZIP(), []int{6}
}

func (x *ASTDependency) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ASTDependency) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

type Library struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Go module to analyze.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The Go module's version.
	Version       string    `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Provide       []*Symbol `protobuf:"bytes,3,rep,name=provide,proto3" json:"provide,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Library) Reset() {
	*x = Library{}
	mi := &file_api_v1_cdn_cdn_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Library) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Library) ProtoMessage() {}

func (x *Library) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_cdn_cdn_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Library.ProtoReflect.Descriptor instead.
func (*Library) Descriptor() ([]byte, []int) {
	return file_api_v1_cdn_cdn_proto_rawDescGZIP(), []int{7}
}

func (x *Library) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Library) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Library) GetProvide() []*Symbol {
	if x != nil {
		return x.Provide
	}
	return nil
}

var File_api_v1_cdn_cdn_proto protoreflect.FileDescriptor

const file_api_v1_cdn_cdn_proto_rawDesc = "" +
	"\n" +
	"\x14api/v1/cdn/cdn.proto\x12\n" +
	"api.v1.cdn\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xac\x01\n" +
	"\x14CreateLibraryRequest\x125\n" +
	"\x04name\x18\x01 \x01(\tB!\x92A\x1aJ\x18\"github.com/gorilla/mux\"\xe2A\x01\x02R\x04name\x12+\n" +
	"\aversion\x18\x02 \x01(\tB\x11\x92A\n" +
	"J\b\"v1.8.1\"\xe2A\x01\x02R\aversion\x12'\n" +
	"\x04test\x18\x03 \x01(\bB\x0e\x92A\aJ\x05false\xe2A\x01\x01H\x00R\x04test\x88\x01\x01B\a\n" +
	"\x05_test\"|\n" +
	"\x16RetrieveLibraryRequest\x125\n" +
	"\x04name\x18\x01 \x01(\tB!\x92A\x1aJ\x18\"github.com/gorilla/mux\"\xe2A\x01\x02R\x04name\x12+\n" +
	"\aversion\x18\x02 \x01(\tB\x11\x92A\n" +
	"J\b\"v1.8.1\"\xe2A\x01\x02R\aversion\"R\n" +
	"$RetrieveSymbolASTDependenciesRequest\x12*\n" +
	"\x06symbol\x18\x01 \x01(\v2\x12.api.v1.cdn.SymbolR\x06symbol\"\\\n" +
	"\x0eSymbolDepGraph\x12&\n" +
	"\x04from\x18\x01 \x01(\v2\x12.api.v1.cdn.SymbolR\x04from\x12\"\n" +
	"\x02to\x18\x02 \x03(\v2\x12.api.v1.cdn.SymbolR\x02to\"\xe2\x01\n" +
	"\x0fDependencyGraph\x125\n" +
	"\x04name\x18\x01 \x01(\tB!\x92A\x1aJ\x18\"github.com/gorilla/mux\"\xe2A\x01\x02R\x04name\x12+\n" +
	"\aversion\x18\x02 \x01(\tB\x11\x92A\n" +
	"J\b\"v1.8.1\"\xe2A\x01\x02R\aversion\x12,\n" +
	"\aprovide\x18\x03 \x03(\v2\x12.api.v1.cdn.SymbolR\aprovide\x12=\n" +
	"\fdependencies\x18\x04 \x03(\v2\x19.api.v1.cdn.ASTDependencyR\fdependencies\"I\n" +
	"\x06Symbol\x12?\n" +
	"\bidentity\x18\x01 \x01(\tB#\x92A\x1cJ\x1a\"internal/stringslite.Cut\"\xe2A\x01\x02R\bidentity\"}\n" +
	"\rASTDependency\x127\n" +
	"\x04from\x18\x01 \x01(\tB#\x92A\x1cJ\x1a\"internal/stringslite.Cut\"\xe2A\x01\x02R\x04from\x123\n" +
	"\x02to\x18\x02 \x03(\tB#\x92A\x1cJ\x1a\"internal/stringslite.Cut\"\xe2A\x01\x02R\x02to\"\x9b\x01\n" +
	"\aLibrary\x125\n" +
	"\x04name\x18\x01 \x01(\tB!\x92A\x1aJ\x18\"github.com/gorilla/mux\"\xe2A\x01\x02R\x04name\x12+\n" +
	"\aversion\x18\x02 \x01(\tB\x11\x92A\n" +
	"J\b\"v1.8.1\"\xe2A\x01\x02R\aversion\x12,\n" +
	"\aprovide\x18\x03 \x03(\v2\x12.api.v1.cdn.SymbolR\aprovide2\xa8\x03\n" +
	"\x03CDN\x12^\n" +
	"\rCreateLibrary\x12 .api.v1.cdn.CreateLibraryRequest\x1a\x13.api.v1.cdn.Library\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/api/v1/cdn\x12g\n" +
	"\x0fRetrieveLibrary\x12\".api.v1.cdn.RetrieveLibraryRequest\x1a\x13.api.v1.cdn.Library\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/cdn/library\x12\x89\x01\n" +
	"\x1dRetrieveSymbolASTDependencies\x120.api.v1.cdn.RetrieveSymbolASTDependenciesRequest\x1a\x1a.api.v1.cdn.SymbolDepGraph\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/cdn/symbol\x12L\n" +
	"\x05Reset\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x13\x82\xd3\xe4\x93\x02\r*\v/api/v1/cdnBFZDgit.cvewatcher.la-ruche.fr/CVEWatcher/godepgraph/api/v1/cdn;apiv1cdnb\x06proto3"

var (
	file_api_v1_cdn_cdn_proto_rawDescOnce sync.Once
	file_api_v1_cdn_cdn_proto_rawDescData []byte
)

func file_api_v1_cdn_cdn_proto_rawDescGZIP() []byte {
	file_api_v1_cdn_cdn_proto_rawDescOnce.Do(func() {
		file_api_v1_cdn_cdn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_cdn_cdn_proto_rawDesc), len(file_api_v1_cdn_cdn_proto_rawDesc)))
	})
	return file_api_v1_cdn_cdn_proto_rawDescData
}

var file_api_v1_cdn_cdn_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_v1_cdn_cdn_proto_goTypes = []any{
	(*CreateLibraryRequest)(nil),                 // 0: api.v1.cdn.CreateLibraryRequest
	(*RetrieveLibraryRequest)(nil),               // 1: api.v1.cdn.RetrieveLibraryRequest
	(*RetrieveSymbolASTDependenciesRequest)(nil), // 2: api.v1.cdn.RetrieveSymbolASTDependenciesRequest
	(*SymbolDepGraph)(nil),                       // 3: api.v1.cdn.SymbolDepGraph
	(*DependencyGraph)(nil),                      // 4: api.v1.cdn.DependencyGraph
	(*Symbol)(nil),                               // 5: api.v1.cdn.Symbol
	(*ASTDependency)(nil),                        // 6: api.v1.cdn.ASTDependency
	(*Library)(nil),                              // 7: api.v1.cdn.Library
	(*emptypb.Empty)(nil),                        // 8: google.protobuf.Empty
}
var file_api_v1_cdn_cdn_proto_depIdxs = []int32{
	5,  // 0: api.v1.cdn.RetrieveSymbolASTDependenciesRequest.symbol:type_name -> api.v1.cdn.Symbol
	5,  // 1: api.v1.cdn.SymbolDepGraph.from:type_name -> api.v1.cdn.Symbol
	5,  // 2: api.v1.cdn.SymbolDepGraph.to:type_name -> api.v1.cdn.Symbol
	5,  // 3: api.v1.cdn.DependencyGraph.provide:type_name -> api.v1.cdn.Symbol
	6,  // 4: api.v1.cdn.DependencyGraph.dependencies:type_name -> api.v1.cdn.ASTDependency
	5,  // 5: api.v1.cdn.Library.provide:type_name -> api.v1.cdn.Symbol
	0,  // 6: api.v1.cdn.CDN.CreateLibrary:input_type -> api.v1.cdn.CreateLibraryRequest
	1,  // 7: api.v1.cdn.CDN.RetrieveLibrary:input_type -> api.v1.cdn.RetrieveLibraryRequest
	2,  // 8: api.v1.cdn.CDN.RetrieveSymbolASTDependencies:input_type -> api.v1.cdn.RetrieveSymbolASTDependenciesRequest
	8,  // 9: api.v1.cdn.CDN.Reset:input_type -> google.protobuf.Empty
	7,  // 10: api.v1.cdn.CDN.CreateLibrary:output_type -> api.v1.cdn.Library
	7,  // 11: api.v1.cdn.CDN.RetrieveLibrary:output_type -> api.v1.cdn.Library
	3,  // 12: api.v1.cdn.CDN.RetrieveSymbolASTDependencies:output_type -> api.v1.cdn.SymbolDepGraph
	8,  // 13: api.v1.cdn.CDN.Reset:output_type -> google.protobuf.Empty
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_v1_cdn_cdn_proto_init() }
func file_api_v1_cdn_cdn_proto_init() {
	if File_api_v1_cdn_cdn_proto != nil {
		return
	}
	file_api_v1_cdn_cdn_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_cdn_cdn_proto_rawDesc), len(file_api_v1_cdn_cdn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_cdn_cdn_proto_goTypes,
		DependencyIndexes: file_api_v1_cdn_cdn_proto_depIdxs,
		MessageInfos:      file_api_v1_cdn_cdn_proto_msgTypes,
	}.Build()
	File_api_v1_cdn_cdn_proto = out.File
	file_api_v1_cdn_cdn_proto_goTypes = nil
	file_api_v1_cdn_cdn_proto_depIdxs = nil
}
